"use client";

import { useState } from "react";
import { createPortal } from "react-dom";
import Swal from "sweetalert2";
import "./CreateBadgeModal.css";

interface Props {
  onClose: () => void;
  onCreated: () => void;
  editData?: any;
}

export default function CreateBadgeModal({ onClose, onCreated, editData }: Props) {
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: editData?.name || "",
    description: editData?.description || "",
    badge_type: editData?.badge_type || "self-declared",
    icon_url: editData?.icon_url || ""
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const token = localStorage.getItem("token");
      const method = editData ? "PATCH" : "POST";
      
      // If editing, include the existing ID. If creating, ID is auto-generated by API.
      const payload = editData ? { _id: editData._id, ...formData } : formData;

      const res = await fetch("/api/admin/badges", {
        method,
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(payload)
      });

      const json = await res.json();
      if (res.ok) {
        Swal.fire({ icon: 'success', title: editData ? 'Updated!' : 'Created!', text: editData ? 'Badge updated!' : 'Badge created!' });
        onCreated();
      } else {
        Swal.fire({ icon: 'error', title: 'Error', text: json.error });
      }
    } catch (err) {
      console.error("Failed to save badge:", err);
      Swal.fire({ icon: 'error', title: 'Error', text: 'Something went wrong' });
    } finally {
      setLoading(false);
    }
  };

  return createPortal(
    <div className="cb-overlay" onClick={onClose}>
      <div className="cb-modal" onClick={(e) => e.stopPropagation()}>
        <button className="cb-close" onClick={onClose}>✕</button>
        <h2 className="cb-title">{editData ? "Edit Badge" : "Create New Badge"}</h2>
        
        <form className="cb-form" onSubmit={handleSubmit}>
          <div className="cb-form-group">
            <label>Badge Name</label>
            <input 
              type="text" 
              required 
              placeholder="e.g. Master Chef"
              value={formData.name}
              onChange={(e) => setFormData({...formData, name: e.target.value})}
            />
          </div>

          <div className="cb-form-group">
            <label>Description</label>
            <textarea 
              required 
              placeholder="What is this badge for?"
              value={formData.description}
              onChange={(e) => setFormData({...formData, description: e.target.value})}
            />
          </div>

          <div className="cb-form-group">
            <label>Badge Type</label>
            <select 
              value={formData.badge_type}
              onChange={(e) => setFormData({...formData, badge_type: e.target.value as any})}
            >
              <option value="self-declared">Self Declared</option>
              <option value="expert-certified">Expert Certified</option>
            </select>
          </div>

          <div className="cb-form-group">
            <label>Icon URL (Image link)</label>
            <input 
              type="text" 
              required 
              placeholder="https://..."
              value={formData.icon_url}
              onChange={(e) => setFormData({...formData, icon_url: e.target.value})}
            />
          </div>

          {formData.icon_url && (
            <div className="cb-preview">
              <p>Icon Preview:</p>
              <img src={formData.icon_url} alt="Preview" onError={(e) => (e.currentTarget.src = "/icon/medal.png")} />
            </div>
          )}

          <div className="cb-actions">
            <button type="button" className="cb-btn cb-btn-cancel" onClick={onClose}>Cancel</button>
            <button type="submit" className="cb-btn cb-btn-save" disabled={loading}>
              {loading ? "Saving..." : (editData ? "Update Badge" : "Create Badge")}
            </button>
          </div>
        </form>
      </div>
    </div>,
    document.body
  );
}
